
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.12

stages:
  - build
  - test

before_script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest test

mypy:
  stage: test
  script:
    - mypy main/

black:
  stage: test
  script:
    - black --diff --check main/

isort:
  stage: test
  script:
    - isort --check-only main/

flask8:
  stage: test
  script:
    - flake8 main/